name: Linux browsers
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install latest Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
    - name: Install Browsertime
      run: npm ci
    - name: Install dependencies
      run: |
        sudo apt-get install net-tools -y
        sudo snap install ffmpeg
        python -m pip install --upgrade --user pip
        python -m pip install --upgrade --user setuptools
        python -m pip install --user pyssim
        python -m pip --version
        python -m pip show Pillow
        python -m pip show pyssim
        python -m pip install virtualenv
        ./browsertime/visualmetrics.py --check
        sudo modprobe ifb numifbs=1
    - name: Browser versions
      run: |
        google-chrome --version
        firefox --version
    # - run: VTENV_OPTS="-p python3" make test
    - name: Test Firefox with throttle
      run: ./bin/browsertime.js -b firefox -n 1 https://www.sitespeed.io --connectivity.profile cable --connectivity.engine throttle --xvfb --firefox.collectMozLog
    - name: Test Chrome with CPU throttle and preURL
      run: ./bin/browsertime.js -b chrome --skipHar -n 1 --preURL https://www.sitespeed.io/ -r header:value --chrome.CPUThrottlingRate 2 --chrome.cdp.performance --xvfb --chrome.enableChromeDriverLog --chrome.collectConsoleLog https://www.sitespeed.io/documentation/
    - name: Test pre/post scripts
      run: ./bin/browsertime.js -b chrome test/navigationscript/measure.js -n 1 --preScript test/prepostscripts/preSample.js --postScript test/prepostscripts/postSample.js --xvfb
    - name: Test navigation and page complete check inactivity
      run: ./bin/browsertime.js -b chrome test/navigationscript/navigateAndStartInTwoSteps.js -n 1 --pageCompleteCheckInactivity --timeToSettle 1000 --xvfb
    - name: Test multi pages
      run: ./bin/browsertime.js -b firefox test/navigationscript/multi.js https://www.sitespeed.io/blog/ -n 1 --xvfb
    - name: Test multi pages with video and visual metrics
      run: ./bin/browsertime.js -b chrome test/navigationscript/multi.js -n 3 --chrome.timeline --video --visualMetrics --visualElements --viewPort 1000x600 --xvfb
    - name: Test Firefox Geckoprofiler
      run: ./bin/browsertime.js -b firefox --firefox.geckoProfiler -n 1 https://www.sitespeed.io/ --spa --xvfb
    - name: Test Firefox with scripting
      run: ./bin/browsertime.js -b firefox test/unifiedscripts/sample.js --xvfb
    - name: Test Chrome with emulated mobile
      run: ./bin/browsertime.js -b chrome --chrome.mobileEmulation.deviceName 'iPhone 6' https://www.sitespeed.io --xvfb
    - name: Test Firefox with web driver nagivation
      run: ./bin/browsertime.js -b firefox -n 1 https://www.sitespeed.io/ --webdriverPageload --xvfb
    - name: Test Chrome with web driver nagivation
      run: ./bin/browsertime.js -b chrome -n 1 https://www.sitespeed.io/ --webdriverPageload --xvfb
    - name: Test navigate to the same URL twice
      run: ./bin/browsertime.js -b chrome test/navigationscript/sameURLTwice.js -n 1 --pageCompleteCheckInactivity --timeToSettle 1000 --xvfb
    - name: Test navigate to the same URL twice by clicking on a link
      run: ./bin/browsertime.js -b chrome test/navigationscript/sameURLTwiceWithClick.js -n 1 --pageCompleteCheckInactivity --timeToSettle 1000 --xvfb
    - name: Test using alias for one URL
      run: ./bin/browsertime.js -b chrome https://www.sitespeed.io/ --urlAlias my_url --xvfb
    - name: Test using alias for multiple URLs
      run: ./bin/browsertime.js -b chrome https://www.sitespeed.io/ https://www.sitespeed.io/documentation/ --urlAlias startPage --urlAlias documentation --xvfb  
    - name: Test collecting Firefox perf statistics
      run: ./bin/browsertime.js -b firefox --firefox.perfStats --xvfb https://www.sitespeed.io/
    - name: Run test with pre-test functionality
      run: ./bin/browsertime.js -b chrome --preWarmServer --xvfb https://www.sitespeed.io/
    - name: Run test with screenshots
      run: ./bin/browsertime.js -b chrome --screenshotLCP --screenshotLS --xvfb https://www.sitespeed.io/